[package]
name = "bufferoverflow"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "simple_overflow"
path = "src/simple_overflow.rs"