[package]
name = "use-after-free"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"

[dependencies]
[[bin]]
name = "use_after_free_safe"
path = "src/use_after_free_safe.rs"

