[package]
name = "race-condition"
version = "0.1.0"
edition = "2021"

[dependencies]
[[bin]]
name = "race_condition"
path = "src/bin/race_condition.rs"

[[bin]]
name = "race_condition_safe"
path = "src/bin/race_condition_safe.rs"